baseURL = 'https://lukeorth.com'
languageCode = 'en-us'
title = 'Luke Orth'
theme = "hugo-theme-minos"
paginate = 6

[params]
    description = "code by Luke Orth"
    menuSinglePages = ["Abouts"]
    menuDirectories = ["Projects"]
    menuGroupByDate = ["Posts"]
    customCss = []
    smartToc = true
    katex = true

    github_url = 'https://github.com/LukeOrth'
    linkedin_url = 'https://linkedin.com/in/lukeorth'
[menu]
[[menu.main]]
  identifier = 'about'
  name = 'about'
  url = '/about/'
  weight = -100
[[menu.main]]
  name = 'projects'
  post = "<span class='alert'>New!</span>"
  url = '/projects/'
  weight = -100

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[taxonomies]
    category = 'categories'
    series = 'series'
    tags = 'tags'
